title: Write the Docs Podcast
description: >
  WTD Podcasts features discussions from members of the Write the Docs community, usually featuring a new guest each time in addition to the regular hosts. Discussions focus on any aspect related to software documentation.
url: http://podcast.writethedocs.org

host: 127.0.0.1
port: 4008

exclude:
  - .idea

permalink: /:year/:month/:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "podcast"
      comments: true

plugins: [jekyll-sitemap, jekyll-mentions, jekyll-redirect-from, jekyll-paginate]

## mp4 videos for fire tv app are hosted here. this field appears in the fab.json template.
## mp4_cdn_url: https://d1pspton2hyndh.cloudfront.net
mp4_cdn_url: http://writethedocs-podcast.s3-website-us-west-2.amazonaws.com

## Values for podcast RSS feed

podcast_subtitle: A discussion podcast based on WTD topics and issues, focused on technical writing and documentation for software products.
podcast_url: http://podcast.writethedocs.org
podcast_album_art: http://podcast.writethedocs.org/assets/img/wtdpodcastlogo.png
podcast_title: Write the Docs Podcast
podcast_owner: Write the Docs Community
podcast_email: writethedocspodcast@gmail.com
podcast_category: Technology
podcast_subcategory_one: Software How-To
podcast_subcategory_two: Tech News
podcast_explicit: "no"
podcast_author: Write the Docs Community
podcast_description: Podcasts for the Write the Docs community. Mostly focused on tech comm, tech writing, UX, IA, and more.
podcast_summary: "Write the Docs is a series of conferences, local meetups, and Slack groups focused on all things related to software documentation. We consider everyone who cares about communication, documentation, and their users to be a member of our community. This can be programmers, tech writers, customer support, marketers, and anyone else who wants people to have great experiences with software. This podcast is focused on topics discussed and debated within this community."
