
info:

- name: Jared Morgan
  website: http://jaredleonmorgan.net
  slack_handle: jaredmorgs
  twitter: http://twitter.com/jaredmorgs
  linkedin: https://www.linkedin.com/in/jaredmorgs
  description: 'Tech writer, prod mgr, and more. Pinball fan, podcaster. <a href="http://jaredleonmorgan.net/">jaredleonmorgan.net</a>'
  image: jared_morgan.jpg
  main_cohost: true

- name: Carlee Potter
  website: http://ilikestreetart.com
  slack_handle: carleecomm
  description: 'Write user manuals out of a love of organisation (& dislike of poor UX). @ Campaign Monitor. <a href="http://ilikestreetart.com/">ilikestreetart.com</a>'
  image: carlee_potter.jpg
  twitter: https://twitter.com/carleecomm
  linkedin: https://www.linkedin.com/in/carleepotter/
  main_cohost: true

- name: Chris Ward
  website: https://chrischinchilla.com/
  slack_handle: chrisward
  description: 'Indep. consultant. Born in England, raised in Aust., live in Berlin. Former programmer. <a href="https://www.gregariousmammal.com/">gregariousmammal.com</a>'
  image: chris_ward.jpg
  linkedin: https://www.linkedin.com/in/chrischinchilla/
  twitter: https://twitter.com/chrischinch
  main_cohost: true

- name: Tom Johnson
  website: https://idratherbewriting.com
  slack_handle: tomjohnson
  twitter: http://twitter.com/tomjohnson
  linkedin: https://www.linkedin.com/in/tomjohnson1492
  description: 'Technical writer at Amazon. Live in SF Bay area. Blogger, podcaster, and pickup baller. <a href="https://idratherbewriting.com">idratherbewriting.com</a>'
  image: tom_johnson.jpg
  main_cohost: true

- name: Eva Jackolis
  website: https://www.linkedin.com/in/eva-jackolis-a31bb3109/
  slack_handle: evalachief
  # twitter: http://twitter.com/evajackolis
  linkedin: https://www.linkedin.com/in/eva-jackolis-a31bb3109/
  description: 'Technical Writer at Seerene in Potsdam. Based in Berlin. Member of WTD Berlin.'
  image: eva_jackolis.png

- name: Pawel Kowaluk
  website: http://pawelkowaluk.brandyourself.com/
  slack_handle: pawelkowaluk
  twitter: https://twitter.com/pawelkowaluk
  linkedin: https://www.linkedin.com/in/pawelkowaluk/?ppe=1
  description: 'Technical Writer in Poland. DITA geek. Passionate about community. <a href="http://pawelkowaluk.brandyourself.com/">pawalkowaluk.brandyourself.com</a>'
  image: pawel_kowaluk.png

- name: Beth Aitman
  website: http://uiwriting.tumblr.com
  slack_handle: beth.aitman
  twitter: https://twitter.com/baitman
  linkedin: https://www.linkedin.com/in/bethaitman
  description: 'Technical writer at @improbableio. Based in England. Passionate about UI design. <a href="http://uiwriting.tumblr.com/">uiwriting.tumblr.com/</a>'
  image: beth_aitman.png

- name: Ellis Pratt
  website: https://www.cherryleaf.com
  slack_handle: ellispratt
  twitter: https://twitter.com/ellispratt
  linkedin: https://www.linkedin.com/in/ellispratt/
  description: 'Director, Consulting Technical Communicator at Cherryleaf. Based near London. Guru for tech comm in Europe. <a href="https://www.cherryleaf.com/">cherryleaf.com</a>'
  image: ellis_pratt.jpg

- name: Kadir Topal
  website: https://redronin.de
  twitter: https://twitter.com/atopal
  linkedin: https://www.linkedin.com/in/kadirtopal/
  description: "Product manager for Mozilla Developer Network's Web Docs project. Based in Germany. <a href=\"https://redronin.de/\">redronin.de/</a>"
  image: kadir_topal.png

- name: Mikey Ariel
  website: http://docsideofthemoon.com
  slack_handle: thatdocslady
  twitter: https://twitter.com/thatdocslady
  linkedin: https://www.linkedin.com/in/thatdocslady/
  description: "Documentation czar and organizer for WTD Europe. Works at Red Hat, lives in Prague. <a href=\"http://docsideofthemoon.com/\">docsideofthemoon.com/</a>"
  image: mikey_ariel.png

- name: Eric Holscher
  website: http://ericholscher.com
  slack_handle: ericholscher
  twitter: https://twitter.com/ericholscher
  linkedin: https://www.linkedin.com/in/eric-holscher-2b975111b/
  description: "Co-founder WTD & <a href=\"https://readthedocs.org/\">Read the Docs</a> platform. The driving force. <a href=\"http://ericholscher.com/\">ericholscher.com/</a>"
  image: eric_holscher.png

- name: Abhinav Asthana
  website: http://getpostman.com
# note: user does not have actual slack handle. added this here for guest_host.html include.
  slack_handle: Abhinav_Asthana
  twitter: https://twitter.com/a85
  linkedin: https://www.linkedin.com/in/abhinavasthana
  description: "Founder and CEO of Postman. On a mission to simplify API development. Innovator and product genius. <a href=\"http://getpostman.com/\">getpostman.com/</a>"
  image: abhinavasthana.png

- name: Carolyn Stransky
  website: https://about.me/carolstran
  slack_handle: carolyn
  twitter: https://twitter.com/carolstran
  linkedin: https://www.linkedin.com/in/carolstran/
  description: "Journalist and JavaScript Developer in Berlin, Germany. Passionate about humanizing docs. <a href=\"https://about.me/carolstran\">about.me/carolstran/</a>"
  image: caroylyn_stransky.jpg

- name: Anett Pozsar
  website: https://twitter.com/katsa23
  slack_handle: anettpozsar
  twitter: https://twitter.com/katsa23
  linkedin: https://www.linkedin.com/in/anettpozsar/
  description: "Hungarian technical Writer at Pronovix. Also in a death metal band. <a href=\"https://twitter.com/katsa23\">@katsa23</a>"
  image: annet_pozsar.jpg

- name: Mark Baker
  website: https://everypageispageone.com
  slack_handle: mbaker.analecta
  twitter: https://twitter.com/mbakeranalecta
  linkedin: https://www.linkedin.com/in/mbakeranalecta/
  description: "Author, <i>Every Page is Page One</i> and <i>Structured Writing</i> <a href=\"https://everypageispageone.com\">everypageispageone.com</a>"
  image: mark_baker.png

- name: Jessica Parsons
  website: https://www.verythorough.com
  slack_handle: verythorough
  twitter: https://twitter.com/verythorough
  linkedin: https://www.linkedin.com/in/verythorough/
  description: "Documentation engineer @netlify. Previously a web developer, now a documentation engineer. <a href=\"https://www.verythorough.com/\">verythorough.com</a>"
  image: jessica_parsons.png

- name: Matt Reiner
  website: https://medium.com/@reinermatthew
  slack_handle: U967DEZBL
  twitter: https://twitter.com/reinermatthew
  linkedin: https://www.linkedin.com/in/matthewreiner/
  description: "Technical writer, storyteller, & Oxford comma user. Currently at K15t. <a href=\"https://medium.com/@reinermatthew/\">medium.com</a>"
  image: matt_reiner.png

- name: Becky Todd
  website: https://twitter.com/beckatodd
  slack_handle: becky
  twitter: https://twitter.com/beckatodd
  linkedin: https://www.linkedin.com/in/toddbecky/
  image: becky_todd.jpg

- name: Giles Gaskell
#  website: https://twitter.com/beckatodd
  slack_handle: gilesgas
  twitter: https://twitter.com/giles_gas
  linkedin: https://www.linkedin.com/in/giles-gaskell-b902773/
  image: giles_gaskell.png

- name: Lucie Le Naour
  slack_handle: lucue_le_naour
#  website: https://twitter.com/beckatodd
#  twitter: https://twitter.com/giles_gas
  linkedin: https://www.linkedin.com/in/lucie-le-naour-97750822/
  image: lucie_le_naour.png

- name: Swapnil Ogale
  website: https://icreatedocs.wordpress.com/
  slack_handle: swapnilogale
  twitter: https://twitter.com/swapnilogale
  linkedin: https://www.linkedin.com/in/swapnilogale/
  image: swapnil_ogale.png

- name: Andrew Head
  website: https://andrewhead.info
  slack_handle: UH9061AG2
  twitter: https://twitter.com/drewmikehead
#  linkedin:
  image: andrew_head.png

- name: Alan Bowman
  website: https://www.linkedin.com/in/ralanbowman/
  slack_handle: U6F5NLPNG
  twitter: https://twitter.com/alanbowman
  linkedin: https://www.linkedin.com/in/ralanbowman
  image: alan_bowman.png

- name: Amy Qualls
  website: http://amyqualls.com/
  slack_handle: AmyQ
  twitter: https://twitter.com/domesticat
  linkedin: https://www.linkedin.com/in/amyqualls/
  image: amy_qualls.png

- name: Cynthia Ng
  website: https://about.me/cynthiang
  slack_handle: arty-chan
  twitter: https://twitter.com/TheRealArty
  linkedin: https://www.linkedin.com/in/cynthiasng/
  image: cynthia_ng.png

- name: Juan Lara
  website: https://twitter.com/JRLtechwriting
  slack_handle: juanl
  twitter: https://twitter.com/JRLtechwriting
  linkedin: https://www.linkedin.com/in/juan-lara/
  image: juan_lara.png
